name: React Test CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: |
        cd updatedFile
        npm install
        npm install --save-dev jest @babel/preset-env @babel/preset-react @testing-library/react @testing-library/jest-dom react react-dom
        
    - name: Update testcase.js location
      run: |
        if [ ! -f frontend/testcase.js ] && [ -f testcase.js ]; then
          mv testcase.js frontend/
        fi
    - name: List frontend directory contents
      run: |
        cd updatedFile
        ls -la
    - name: Display testcase.js content
      run: |
        cd updatedFile
        cat testcase.js
    - name: Create Babel config
      run: |
        cd updatedFile
        echo '{
          "presets": ["@babel/preset-env", "@babel/preset-react"]
        }' > .babelrc
    - name: Create Jest config
      run: |
        cd frontend
        echo "module.exports = {
          testEnvironment: 'jsdom',
          testEnvironmentOptions: {
            customExportConditions: ['node', 'node-addons'],
          },
          setupFilesAfterEnv: ['@testing-library/jest-dom'],
          transform: {
            '^.+\\.(js|jsx)$': 'babel-jest'
          },
          testMatch: ['**/testcase.js']
          rootDir: '.'
        };" > jest.config.js
    - name: Run tests from testcase.js
      run: |
        cd updatedFile
        npx jest --config=jest.config.js --verbose
